services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync 
          path: .
          target: /usr/src/app

        - action: rebuild
          path: package.json


































