services:
  backend:
    extends:
      file: ${BACKEND_PATH}
      service: server 
    depends_on: 
      postgres: 
        condition: service_healthy 
  postgres:
    extends:
      file: ${BACKEND_PATH}
      service: postgres 
  frontend:
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync 
          path: .
          target: /usr/src/app
        - action: rebuild
          path: package.json
        - action: rebuild
          path: bun.lockb

